.TH "alarm-clock-applet" "1"
.SH NAME
.B alarm-clock-applet
\- Alarm Clock for your notification area
.SH SYNOPSIS
.B alarm-clock-applet
.SH DESCRIPTION
.B alarm-clock-applet
is an applet providing alarm clock functionality which lives within the
notification area. It is easy to use yet powerful with support for multiple and
repeatable alarms, as well as snoozing, and a flexible notification system.

Two types of alarms are supported: Alarm Clocks, and Timers. Notification can be
done by either playing a sound, launching an application, showing a
notification bubble, or any combination of the aforementioned options.

This application does not take any command line options.
.SH COPYRIGHT
.B alarm-clock-applet
was written by Johannes H. Jensen <joh@pseudoberries.com> and is licensed under
the GNU General Public License, version 2 or any later version published by the
Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL-2
